---
- name: Install Apache on Webservers
  hosts: webservers
  become: true

  tasks:
    - name: Install required packages
      dnf:
        name: httpd
        state: latest

    - name: Start httpd
      service:
        name: httpd
        state: started
        enabled: true

    - name: Allow http access via firewall
      ansible.posix.firewalld:
        service: http
        state: enabled
        immediate: yes
        permanent: yes

    - name: Install custom index.html
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
        mode: 0644
      notify:
        - restart httpd

  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
